### ISSUE TITLE
增加清晰度选项

### ISSUE THREAD

**Issue by yeezylife** [injahow/bilibili-parse#1]
下载脚本很清爽,也很好用,我再也不用为了一个下载功能安装一个特别臃肿的脚本/扩展
但是我发现点击"请求地址"=>"下载视频"之后就直接开始下载了,如果能在开始下载之前增加一个清晰度选项会不会好一些

**Comment by injahow** [comment]
清晰度是使用播放器的当前选项，
修改清晰度即更改播放器清晰度再请求后下载即可
我觉得没有必要添加，因为平时播放的清晰度即为需要下载的清晰度

**Comment by yeezylife** [comment]
多数脚本/扩展 的下载功能还是带清晰度选项的(只是过于臃肿),在播放器里修改有点慢,而且如果在线播放与下载的清晰度需求不一样的人 改完了还得再改回去...

**Comment by injahow** [comment]
请问多数脚本是选择清晰度的（工作流程）
就此脚本而言请求地址后，能够获取所有支持的清晰度参数，如果下载的清晰度不一样，就必须再次请求
又或者请求前就设置一个清晰度（所有情况），但又可能视频没有这个清晰度导致请求可能出现问题
当下唯一可选即是动态设置清晰度选项（匹配播放器的选项），但问题是清晰度选项框该如何放置？

**Comment by injahow** [comment]
请问多数脚本是如何选择清晰度的（工作流程）
就此脚本而言请求地址后，能够获取所有支持的清晰度参数，如果下载的清晰度不一样，就必须再次请求
又或者请求前就设置一个清晰度（所有情况），但又可能视频没有这个清晰度导致请求可能出现问题
当下唯一可选即是动态设置清晰度选项（匹配播放器的选项），但问题是清晰度选项框该如何放置？

**Comment by yeezylife** [comment]
我试过bilibilihelper(扩展)
[https://github.com/bilibili-helper/bilibili-helper-o](url)
和bilibili-evolved(脚本,功能太多,开主页需要4秒)
[https://github.com/the1812/Bilibili-Evolved](url)
我自己再找找吧..

**Comment by injahow** [comment]
综合考虑了一下，决定只在批量下载里面支持切换清晰度，仅支持使用rpc下载

**Comment by yeezylife** [comment]
> 综合考虑了一下，决定只在批量下载里面支持切换清晰度，仅支持使用rpc下载

酷,你的脚本我用了一段时间..快也有快的好,一点就来也是一种好的体验,清晰度我自己找个折中的..
