### ISSUE TITLE
有些视频在网页里面就有播放链接，能整合在一起么？

### ISSUE THREAD

**Issue by panda-mute** [injahow/bilibili-parse#10]
window.\_\_playinfo\_\_={"code":0,"message":"0","ttl":1,"data":{"from":"local","result":"suee","message":"","quality":................

**Comment by injahow** [comment]
测试了一下，这个数据好像只在第一次加载页面时设置，页面内的异步切p不会更新，不便于使用

**Comment by injahow** [comment]
api请求爬网页数据比较占资源，其他python之类的本地脚本可以考虑使用
