### ISSUE TITLE
B站支持了8K，不知道能否获得8K的下载链接

### ISSUE THREAD

**Issue by Hotinosin** [injahow/bilibili-parse#4]
https://www.bilibili.com/video/BV1KS4y197BN
新华社的8K获取链接好像只能到4K

**Comment by injahow** [comment]
> https://www.bilibili.com/video/BV1KS4y197BN 新华社的8K获取链接好像只能到4K

ok，因为清晰度参数只设置到120（4k），准备添加其余格式的支持

**Comment by injahow** [comment]
分析发现只有dash源有8k类型，需要下载请切换CDN或使用RPC接口

**Comment by Hotinosin** [comment]
> 分析发现只有dash源有8k类型，需要下载请切换CDN或使用RPC接口
测试了Dash模式下可以下载8K视频，但是缺失音频轨道，点击下载音频还是下载的.4s视频轨道

**Comment by injahow** [comment]
音频问题为脚本bug，请更新至1.8.5版本

**Comment by Hotinosin** [comment]
> 音频问题为脚本bug，请更新至1.8.5版本
目前版本是1.8.5 浏览器是Safari
