### ISSUE TITLE
b站脚本在跳转AriaNg时，会自动通过HTTP连接Aria2，建议改成Websocket

### ISSUE THREAD

**Issue by jbxiaoyu** [injahow/bilibili-parse#6]
由于Chrome最近的安全更新，跨域请求被严格禁止。因此任何第三方搭建的AriaNg（如[脚本中使用的injahow服务器](http://ariang.injahow.com/)），均不能通过HTTP与本地的aria2服务器连接，但Websocket不受影响。

而这个脚本会自动让AriaNg使用HTTP POST连接，望改成Websocket连接。

详见 https://github.com/mayswind/AriaNg/issues/624

**Comment by injahow** [comment]
> 由于Chrome最近的安全更新，跨域请求被严格禁止。因此任何第三方搭建的AriaNg（如[脚本中使用的injahow服务器](http://ariang.injahow.com/)），均不能通过HTTP与本地的aria2服务器连接，但Websocket不受影响。
> 
> 而这个脚本会自动让AriaNg使用HTTP POST连接，望改成Websocket连接。
> 
> 详见 [mayswind/AriaNg#624](https://github.com/mayswind/AriaNg/issues/624)

但我在本地测试未发现异常，无论是127.0.0.1还是192.168.1.1之类的都可正常发送http请求，可否详细描述你的问题

**Comment by jbxiaoyu** [comment]
> > 由于Chrome最近的安全更新，跨域请求被严格禁止。因此任何第三方搭建的AriaNg（如[脚本中使用的injahow服务器](http://ariang.injahow.com/)），均不能通过HTTP与本地的aria2服务器连接，但Websocket不受影响。
> > 而这个脚本会自动让AriaNg使用HTTP POST连接，望改成Websocket连接。
> > 详见 [mayswind/AriaNg#624](https://github.com/mayswind/AriaNg/issues/624)
> 
> 但我在本地测试未发现异常，无论是127.0.0.1还是192.168.1.1之类的都可正常发送http请求，可否详细描述你的问题

我猜你的Chrome版本应该比较低，如果更新到最新版就不行了。你可以看下我在AriaNg底下提交的issue。
https://github.com/mayswind/AriaNg/issues/646

**Comment by injahow** [comment]
> > > 由于Chrome最近的安全更新，跨域请求被严格禁止。因此任何第三方搭建的AriaNg（如[脚本中使用的injahow服务器](http://ariang.injahow.com/)），均不能通过HTTP与本地的aria2服务器连接，但Websocket不受影响。
> > > 而这个脚本会自动让AriaNg使用HTTP POST连接，望改成Websocket连接。
> > > 详见 [mayswind/AriaNg#624](https://github.com/mayswind/AriaNg/issues/624)
> > 
> > 
> > 但我在本地测试未发现异常，无论是127.0.0.1还是192.168.1.1之类的都可正常发送http请求，可否详细描述你的问题
> 
> 我猜你的Chrome版本应该比较低，如果更新到最新版就不行了。你可以看下我在AriaNg底下提交的issue。 [mayswind/AriaNg#646](https://github.com/mayswind/AriaNg/issues/646)

好吧，之前我确认过浏览器是最新的，但今天好像就抽风只能ws连接了，有空再改改脚本，添加rpc请求类型选项

**Comment by injahow** [comment]
已对脚本进行逻辑优化，请查看1.8.8
