### ISSUE TITLE
Mac下使用Safari浏览器油猴脚本无法调用PRC服务

### ISSUE THREAD

**Issue by Hotinosin** [injahow/bilibili-parse#8]
在Chorme中是可以成功调用的，但是Safari下会提示网络异常以及请检查PRC服务
想问下有办法可以解决吗（是不是safari没有Motrix插件导致？

**Comment by injahow** [comment]
我没有Safari无法测试，应该不是Motrix插件的问题，你可以尝试使用ariang页面进行连接（进入方法：清空rpc的域名设置）

**Comment by Hotinosin** [comment]
> 我没有Safari无法测试，应该不是Motrix插件的问题，你可以尝试使用ariang页面进行连接（进入方法：清空rpc的域名设置）

在ariang页面是显示连接成功，但是点击下载视频就提示检查PRC服务

**Comment by injahow** [comment]
> > 我没有Safari无法测试，应该不是Motrix插件的问题，你可以尝试使用ariang页面进行连接（进入方法：清空rpc的域名设置）
> 
> 在ariang页面是显示连接成功，但是点击下载视频就提示检查PRC服务

清空rpc的域名设置，保存设置，然后再点下载视频，会自动打开ariang页面，然后使用ariang下载，脚本执行流程有问题？

**Comment by Hotinosin** [comment]
> > > 我没有Safari无法测试，应该不是Motrix插件的问题，你可以尝试使用ariang页面进行连接（进入方法：清空rpc的域名设置）
> > 
> > 
> > 在ariang页面是显示连接成功，但是点击下载视频就提示检查PRC服务
> 
> 清空rpc的域名设置，保存设置，然后再点下载视频，会自动打开ariang页面，然后使用ariang下载，脚本执行流程有问题？

把PRC配置清空了之后调用ariang之后可以成功下载，感谢🙏🏻
