### ISSUE TITLE
format为mp4只能获取360p链接

### ISSUE THREAD

**Issue by jcdomt** [injahow/bilibili-parse#9]
无论 q 参数怎么设置，都只能获取16
otype设置为json后 accept_quarlty 有四种，但始终无法设置
用的就是大佬测试站的api

**Comment by ScarletDor** [comment]
我也发现是这个问题，求大佬解答一下qaq
@injahow

**Comment by ScarletDor** [comment]
我自己搭建了一个是可以用的，不麻烦大佬啦

**Comment by injahow** [comment]
看了一下，是cookie造成的，b站可能改了mp4接口的鉴权，未登录的cookie是可以正常获取的
